export { default as StripeCatalog } from "./admin/Catalog/StripeCatalog";
export { default as Catalog } from "./admin/Catalog/Catalog";
export { default as Home } from "./public/Home/Home";
export { default as Product } from "./public/Product/Product";
export { default as Cart } from "./public/Cart/Cart";
export { default as Shop } from "./public/Shop/Shop";
// export { default as Profile } from "./public/Profile/Profile";
// export { default as Auth } from "./public/Auth/Auth";
// export { default as Login } from "./public/Auth/Login/Login";
// export { default as Register } from "./public/Auth/Register/Register";
// export { default as ResetPassword } from "./public/Auth/ResetPassword/ResetPassword";
// export { default as ForgotPassword } from "./public/Auth/ForgotPassword/ForgotPassword";
// export { default as Connect } from "./public/Connect/Connect";
// export { default as Orders } from "./public/Orders/Orders";
// export { default as Checkout } from "./public/Checkout/Success";
// export { default as ItemFull } from "./public/Shop/ItemFull/ItemFull";
